version: '2'
services:
  teste-front:
    container_name: teste.front
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./node/:/home/node/app
    expose:
      - "8081"
    command: "npm start"
    networks:
      - teste-net
  teste-back:
    container_name: teste.api
    image: ertfly/php7.4.9-apache-buster
    build: .
    restart: always
    ports:
      - '8016:80'
    volumes:
      - ./app/:/app
    networks:
      - teste-net
  teste-db:
    container_name: teste.db
    image: mongo:4.4.6
    command: mongod --serviceExecutor adaptive
    restart: always
    ports:
      - '27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=teste
      - MONGO_INITDB_ROOT_PASSWORD=Teste@3661
      - MONGO_INITDB_DATABASE=teste
    networks:
      - teste-net
    volumes:
      - ./db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      
networks:
  teste-net:
    external: true